/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiImportsRouteImport } from './routes/api.imports'
import { Route as ApiTransactionsTransactionIdClassificationRouteImport } from './routes/api.transactions.$transactionId.classification'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportsRoute = ApiImportsRouteImport.update({
  id: '/api/imports',
  path: '/api/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsTransactionIdClassificationRoute =
  ApiTransactionsTransactionIdClassificationRouteImport.update({
    id: '/api/transactions/$transactionId/classification',
    path: '/api/transactions/$transactionId/classification',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/transactions': typeof TransactionsRoute
  '/api/imports': typeof ApiImportsRoute
  '/api/transactions/$transactionId/classification': typeof ApiTransactionsTransactionIdClassificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/transactions': typeof TransactionsRoute
  '/api/imports': typeof ApiImportsRoute
  '/api/transactions/$transactionId/classification': typeof ApiTransactionsTransactionIdClassificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/transactions': typeof TransactionsRoute
  '/api/imports': typeof ApiImportsRoute
  '/api/transactions/$transactionId/classification': typeof ApiTransactionsTransactionIdClassificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/transactions'
    | '/api/imports'
    | '/api/transactions/$transactionId/classification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/transactions'
    | '/api/imports'
    | '/api/transactions/$transactionId/classification'
  id:
    | '__root__'
    | '/'
    | '/transactions'
    | '/api/imports'
    | '/api/transactions/$transactionId/classification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiImportsRoute: typeof ApiImportsRoute
  ApiTransactionsTransactionIdClassificationRoute: typeof ApiTransactionsTransactionIdClassificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imports': {
      id: '/api/imports'
      path: '/api/imports'
      fullPath: '/api/imports'
      preLoaderRoute: typeof ApiImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/$transactionId/classification': {
      id: '/api/transactions/$transactionId/classification'
      path: '/api/transactions/$transactionId/classification'
      fullPath: '/api/transactions/$transactionId/classification'
      preLoaderRoute: typeof ApiTransactionsTransactionIdClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TransactionsRoute: TransactionsRoute,
  ApiImportsRoute: ApiImportsRoute,
  ApiTransactionsTransactionIdClassificationRoute:
    ApiTransactionsTransactionIdClassificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
